"use client";

import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Boxes, ClipboardList, PackagePlus, Plus, Send, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Organization } from "./AdminWorkspace";

export type InventoryItem = { id: string; name: string; category: string; unit: string; quantity_on_hand: number; reorder_level: number; storage_location: string | null; notes: string; created_at: string };
export type EquipmentRequest = { id: string; organization_id: string; inventory_item_id: string; quantity_requested: number; needed_at: string | null; status: "pending" | "approved" | "fulfilled" | "rejected" | "cancelled"; notes: string; created_at: string };
export type InventoryTransaction = { id: number; inventory_item_id: string; quantity_change: number; reason: string; organization_id: string | null; notes: string | null; created_at: string };

const inputClass = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-ink outline-none transition focus:border-feu-green focus:ring-2 focus:ring-feu-green/15";
const requestStyles: Record<EquipmentRequest["status"], string> = { pending: "bg-amber-100 text-amber-800", approved: "bg-sky-100 text-sky-700", fulfilled: "bg-emerald-100 text-emerald-800", rejected: "bg-red-100 text-red-700", cancelled: "bg-slate-100 text-slate-600" };

export default function InventoryManager({ initialItems, initialRequests, initialTransactions, organizations }: { initialItems: InventoryItem[]; initialRequests: EquipmentRequest[]; initialTransactions: InventoryTransaction[]; organizations: Organization[] }) {
  const [tab, setTab] = useState<"items" | "requests">("items");
  const [items, setItems] = useState(initialItems);
  const [requests, setRequests] = useState(initialRequests);
  const [transactions, setTransactions] = useState(initialTransactions);
  const [creatingItem, setCreatingItem] = useState(false);
  const [adjustingItem, setAdjustingItem] = useState<InventoryItem | null>(null);
  const [creatingRequest, setCreatingRequest] = useState(false);
  const [notice, setNotice] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const organizationsById = useMemo(() => new Map(organizations.map((organization) => [organization.id, organization])), [organizations]);
  const itemsById = useMemo(() => new Map(items.map((item) => [item.id, item])), [items]);
  const lowStock = items.filter((item) => item.quantity_on_hand <= item.reorder_level).length;
  const pendingRequests = requests.filter((request) => request.status === "pending").length;

  function showNotice(kind: "success" | "error", text: string) { setNotice({ kind, text }); window.setTimeout(() => setNotice(null), 4500); }

  async function createItem(values: Omit<InventoryItem, "id" | "quantity_on_hand" | "created_at">) {
    const supabase = createClient();
    const { data, error } = await supabase.from("inventory_items").insert(values).select("id,name,category,unit,quantity_on_hand,reorder_level,storage_location,notes,created_at").single();
    if (error) throw error;
    setItems((current) => [...current, data as InventoryItem].sort((left, right) => left.name.localeCompare(right.name)));
    setCreatingItem(false); showNotice("success", `${data.name} was added to inventory.`);
  }

  async function adjustStock(item: InventoryItem, values: { change: number; reason: string; organizationId: string | null; notes: string }) {
    const supabase = createClient();
    const { data, error } = await supabase.rpc("record_inventory_adjustment", { target_item_id: item.id, adjustment: values.change, adjustment_reason: values.reason, target_organization_id: values.organizationId, adjustment_notes: values.notes });
    if (error) throw error;
    const createdAt = new Date().toISOString();
    setItems((current) => current.map((currentItem) => currentItem.id === item.id ? { ...currentItem, quantity_on_hand: data as number } : currentItem));
    setTransactions((current) => [{ id: Date.now(), inventory_item_id: item.id, quantity_change: values.change, reason: values.reason, organization_id: values.organizationId, notes: values.notes || null, created_at: createdAt }, ...current]);
    setAdjustingItem(null); showNotice("success", `${item.name} now has ${data} ${item.unit}${data === 1 ? "" : "s"}.`);
  }

  async function createRequest(values: { organization_id: string; inventory_item_id: string; quantity_requested: number; needed_at: string | null; notes: string }) {
    const supabase = createClient();
    const { data, error } = await supabase.from("equipment_requests").insert(values).select("id,organization_id,inventory_item_id,quantity_requested,needed_at,status,notes,created_at").single();
    if (error) throw error;
    setRequests((current) => [data as EquipmentRequest, ...current]);
    setCreatingRequest(false); showNotice("success", "Equipment request recorded.");
  }

  async function updateRequest(request: EquipmentRequest, action: "approved" | "rejected" | "cancelled" | "fulfilled") {
    const supabase = createClient();
    const { data, error } = action === "fulfilled"
      ? await supabase.rpc("fulfill_equipment_request", { target_request_id: request.id })
      : await supabase.rpc("update_equipment_request_status", { target_request_id: request.id, next_status: action });
    if (error) return showNotice("error", error.message);
    setRequests((current) => current.map((item) => item.id === request.id ? { ...item, status: action } : item));
    if (action === "fulfilled") {
      const item = itemsById.get(request.inventory_item_id);
      if (item) setItems((current) => current.map((inventoryItem) => inventoryItem.id === item.id ? { ...inventoryItem, quantity_on_hand: data as number } : inventoryItem));
    }
    showNotice("success", `Request ${action}.`);
  }

  return <div>
    {notice && <div role="status" className={`fixed right-5 top-5 z-[70] max-w-sm rounded-2xl px-5 py-4 text-sm font-semibold shadow-xl ${notice.kind === "success" ? "bg-feu-moss text-white" : "bg-red-600 text-white"}`}>{notice.text}</div>}
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Inventory items" value={items.length} icon={Boxes} color="bg-feu-green/10 text-feu-green" /><Metric label="Low stock" value={lowStock} icon={PackagePlus} color="bg-red-100 text-red-700" /><Metric label="Pending RSO requests" value={pendingRequests} icon={ClipboardList} color="bg-gold-default/20 text-feu-moss" /></div>
    <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex rounded-xl bg-slate-100 p-1"><button type="button" onClick={() => setTab("items")} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === "items" ? "bg-white text-feu-green shadow-sm" : "text-slate-500"}`}>Inventory</button><button type="button" onClick={() => setTab("requests")} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === "requests" ? "bg-white text-feu-green shadow-sm" : "text-slate-500"}`}>RSO requests</button></div><div className="flex gap-2">{tab === "items" ? <><button type="button" onClick={() => setCreatingItem(true)} className="rounded-xl border border-feu-green/25 px-4 py-2.5 text-sm font-bold text-feu-green"><Plus className="mr-1 inline h-4 w-4" /> New item</button><button type="button" onClick={() => setCreatingRequest(true)} disabled={!items.length} className="btn-gold disabled:opacity-50"><Send className="h-4 w-4" /> RSO request</button></> : <button type="button" onClick={() => setCreatingRequest(true)} disabled={!items.length} className="btn-gold disabled:opacity-50"><Send className="h-4 w-4" /> Record request</button>}</div></div>
    {tab === "items" ? <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-ink">Equipment stock</h2></div>{items.length ? <div className="divide-y divide-slate-100">{items.map((item) => <article key={item.id} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-ink">{item.name}</h3>{item.quantity_on_hand <= item.reorder_level && <span className="rounded-full bg-red-100 px-2 py-1 text-[0.6rem] font-black uppercase text-red-700">Low stock</span>}</div><p className="mt-1 text-xs text-slate-500">{item.category} · {item.storage_location || "Location not set"} · reorder at {item.reorder_level}</p></div><div className="flex items-center gap-3"><p className="text-right"><span className="block text-xl font-black text-ink">{item.quantity_on_hand}</span><span className="text-xs text-slate-500">{item.unit}{item.quantity_on_hand === 1 ? "" : "s"}</span></p><button type="button" onClick={() => setAdjustingItem(item)} className="rounded-xl border border-feu-green/25 px-3 py-2 text-xs font-bold text-feu-green">Adjust</button></div></article>)}</div> : <Empty text="Add your first equipment item to begin tracking stock." />}</section><TransactionPanel transactions={transactions} itemsById={itemsById} organizationsById={organizationsById} /></div> : <RequestList requests={requests} itemsById={itemsById} organizationsById={organizationsById} onAction={updateRequest} />}
    {creatingItem && <NewItemDialog onClose={() => setCreatingItem(false)} onSave={createItem} />}{adjustingItem && <AdjustDialog item={adjustingItem} organizations={organizations} onClose={() => setAdjustingItem(null)} onSave={adjustStock} />}{creatingRequest && <RequestDialog items={items} organizations={organizations} onClose={() => setCreatingRequest(false)} onSave={createRequest} />}
  </div>;
}

function Metric({ label, value, icon: Icon, color }: { label: string; value: number; icon: typeof Boxes; color: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><p className="mt-4 text-2xl font-black text-ink">{value}</p><p className="mt-1 text-sm font-semibold text-slate-500">{label}</p></article>; }
function Empty({ text }: { text: string }) { return <p className="m-5 rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">{text}</p>; }
function TransactionPanel({ transactions, itemsById, organizationsById }: { transactions: InventoryTransaction[]; itemsById: Map<string, InventoryItem>; organizationsById: Map<string, Organization> }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-ink">Recent adjustments</h2><div className="mt-4 space-y-4">{transactions.length ? transactions.slice(0, 8).map((transaction) => <div key={transaction.id} className="border-l-2 border-feu-green/20 pl-3"><p className="text-sm font-bold text-ink">{transaction.quantity_change > 0 ? "+" : ""}{transaction.quantity_change} · {itemsById.get(transaction.inventory_item_id)?.name || "Inventory item"}</p><p className="mt-1 text-xs text-slate-500">{transaction.reason}{transaction.organization_id ? ` · ${organizationsById.get(transaction.organization_id)?.acronym || "RSO"}` : ""}</p><p className="mt-1 text-xs text-slate-400">{formatDate(transaction.created_at)}</p></div>) : <p className="text-sm text-slate-500">No stock adjustments yet.</p>}</div></section>; }
function RequestList({ requests, itemsById, organizationsById, onAction }: { requests: EquipmentRequest[]; itemsById: Map<string, InventoryItem>; organizationsById: Map<string, Organization>; onAction: (request: EquipmentRequest, action: "approved" | "rejected" | "cancelled" | "fulfilled") => Promise<void> }) { return <div className="mt-5 space-y-3">{requests.length ? requests.map((request) => { const item = itemsById.get(request.inventory_item_id); const organization = organizationsById.get(request.organization_id); return <article key={request.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-ink">{organization?.name || "RSO request"}</h2><span className={`rounded-full px-2 py-1 text-[0.6rem] font-black uppercase ${requestStyles[request.status]}`}>{request.status}</span></div><p className="mt-2 text-sm text-slate-600">{request.quantity_requested} {item?.unit || "item"}{request.quantity_requested === 1 ? "" : "s"} · <strong>{item?.name || "Inventory item"}</strong></p>{request.needed_at && <p className="mt-1 text-xs text-slate-500">Needed: {new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" }).format(new Date(request.needed_at))}</p>}{request.notes && <p className="mt-3 text-sm leading-6 text-slate-500">{request.notes}</p>}</div>{["pending", "approved"].includes(request.status) && <div className="flex flex-wrap gap-2 sm:max-w-72 sm:justify-end">{request.status === "pending" && <><button type="button" onClick={() => void onAction(request, "approved")} className="rounded-xl bg-feu-green px-3 py-2 text-xs font-bold text-white">Approve</button><button type="button" onClick={() => void onAction(request, "rejected")} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Reject</button></>}<button type="button" onClick={() => void onAction(request, "fulfilled")} className="rounded-xl bg-gold-default px-3 py-2 text-xs font-bold text-feu-moss">Fulfill & issue</button><button type="button" onClick={() => void onAction(request, "cancelled")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">Cancel</button></div>}</div></article>; }) : <Empty text="No RSO equipment requests have been recorded." />}</div>; }
function Dialog({ title, subtitle, children, onClose }: { title: string; subtitle: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[60] flex items-end justify-end bg-ink/45 backdrop-blur-sm sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[96vh] w-full overflow-y-auto rounded-t-3xl bg-cloud shadow-2xl sm:max-w-xl sm:rounded-3xl"><div className="sticky top-0 flex items-start justify-between border-b border-slate-200 bg-white px-6 py-5"><div><h2 className="text-xl font-black text-ink">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></div>{children}</div></div>; }
function NewItemDialog({ onClose, onSave }: { onClose: () => void; onSave: (values: Omit<InventoryItem, "id" | "quantity_on_hand" | "created_at">) => Promise<void> }) { const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await onSave({ name: String(data.get("name")), category: String(data.get("category")) || "General", unit: String(data.get("unit")) || "piece", reorder_level: Number(data.get("reorder_level") || 0), storage_location: String(data.get("storage_location")) || null, notes: String(data.get("notes")) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not add item."); setSaving(false); } } return <Dialog title="Add inventory item" subtitle="New items begin at zero stock; use Adjust to record the opening count." onClose={onClose}><form onSubmit={submit} className="space-y-5 p-6"><Field label="Item name"><input name="name" required minLength={2} className={inputClass} placeholder="e.g. Folding chair" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><input name="category" className={inputClass} placeholder="e.g. Furniture" /></Field><Field label="Unit"><input name="unit" defaultValue="piece" className={inputClass} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Reorder level"><input name="reorder_level" type="number" min="0" defaultValue="0" className={inputClass} /></Field><Field label="Storage location"><input name="storage_location" className={inputClass} placeholder="e.g. SCC cabinet" /></Field></div><Field label="Notes"><textarea name="notes" rows={3} className={inputClass} /></Field>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Actions onClose={onClose} saving={saving} label="Add item" /></form></Dialog>; }
function AdjustDialog({ item, organizations, onClose, onSave }: { item: InventoryItem; organizations: Organization[]; onClose: () => void; onSave: (item: InventoryItem, values: { change: number; reason: string; organizationId: string | null; notes: string }) => Promise<void> }) { const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); const change = Number(data.get("change")); if (!Number.isInteger(change) || change === 0) { setError("Enter a non-zero whole-number adjustment."); setSaving(false); return; } try { await onSave(item, { change, reason: String(data.get("reason")), organizationId: String(data.get("organization_id")) || null, notes: String(data.get("notes")) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not adjust stock."); setSaving(false); } } return <Dialog title={`Adjust ${item.name}`} subtitle={`Current stock: ${item.quantity_on_hand} ${item.unit}${item.quantity_on_hand === 1 ? "" : "s"}`} onClose={onClose}><form onSubmit={submit} className="space-y-5 p-6"><Field label="Quantity change"><input name="change" required type="number" step="1" className={inputClass} placeholder="Use + for restock, − for issue" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Reason"><select name="reason" defaultValue="restock" className={inputClass}><option value="restock">Restock</option><option value="issue">Issue</option><option value="return">Return</option><option value="correction">Correction</option><option value="donation">Donation</option></select></Field><Field label="Related RSO (optional)"><select name="organization_id" defaultValue="" className={inputClass}><option value="">None</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></Field></div><Field label="Notes"><textarea name="notes" rows={3} className={inputClass} placeholder="Why was stock adjusted?" /></Field>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Actions onClose={onClose} saving={saving} label="Record adjustment" /></form></Dialog>; }
function RequestDialog({ items, organizations, onClose, onSave }: { items: InventoryItem[]; organizations: Organization[]; onClose: () => void; onSave: (values: { organization_id: string; inventory_item_id: string; quantity_requested: number; needed_at: string | null; notes: string }) => Promise<void> }) { const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await onSave({ organization_id: String(data.get("organization_id")), inventory_item_id: String(data.get("inventory_item_id")), quantity_requested: Number(data.get("quantity_requested")), needed_at: data.get("needed_at") ? new Date(String(data.get("needed_at"))).toISOString() : null, notes: String(data.get("notes")) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not record request."); setSaving(false); } } return <Dialog title="Record RSO equipment request" subtitle="Create a traceable request before issuing stock." onClose={onClose}><form onSubmit={submit} className="space-y-5 p-6"><Field label="Requesting RSO"><select name="organization_id" required className={inputClass}>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></Field><Field label="Equipment item"><select name="inventory_item_id" required className={inputClass}>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.quantity_on_hand} available</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Quantity requested"><input name="quantity_requested" type="number" min="1" required className={inputClass} /></Field><Field label="Needed by"><input name="needed_at" type="date" className={inputClass} /></Field></div><Field label="Request notes"><textarea name="notes" rows={3} className={inputClass} placeholder="Purpose, event, pickup details…" /></Field>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Actions onClose={onClose} saving={saving} label="Record request" /></form></Dialog>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-bold text-ink">{label}{children}</label>; }
function Actions({ onClose, saving, label }: { onClose: () => void; saving: boolean; label: string }) { return <div className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button type="button" onClick={onClose} className="rounded-xl px-5 py-3 text-sm font-bold text-slate-500">Cancel</button><button type="submit" disabled={saving} className="btn-green disabled:opacity-60">{saving ? "Saving…" : label}</button></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
